### ISSUE TITLE
Update swapped shareholder's holderIndex

### ISSUE THREAD

**Issue by mohoff** [davesag/ERC884-reference-implementation#20]
Hi,
just going through the reference implementation. In your current implementation, the holder index of the swapped (last) address in `shareholders` is not updated on pruning `addr`, although it changes from `holderIndex[shareholders.length-1]` to `holderIndex[addr]`.

I think after [L351](https://github.com/davesag/ERC884-reference-implementation/blob/develop/contracts/token/ERC884/ERC884ReferenceImpl.sol#L351) there should be a line:

```solidity
holderIndices[shareholders[shareholders.length - 1]] = holderIndices[addr]
```
Please let me know if I'm wrong in this.

**Comment by davesag** [comment]
Thanks for spotting that @mohoff 

I have added you as a collaborator and would invite you to review PR #21 when you get a chance.

**Comment by mohoff** [comment]
Cool, thanks, looks good!
